### ISSUE TITLE
cannot import name 'igalib' from 'igakit'

### ISSUE THREAD

**Issue by Yihao-Shi** [dalcinl/igakit#6]
I cannot run igakit after I finish installing it (`pip install .`). The error reports:
```
Traceback (most recent call last):
  File "/home/Users/work/SourceCode/petIGA/igakit/demo/bentpipe.py", line 1, in <module>
    from igakit.cad import *
  File "/home/Users/work/SourceCode/petIGA/igakit/igakit/cad.py", line 2, in <module>
    from igakit.nurbs import NURBS
  File "/home/Users/work/SourceCode/petIGA/igakit/igakit/nurbs.py", line 3, in <module>
    from igakit import igalib as _igalib
ImportError: cannot import name 'igalib' from 'igakit' (/home/Users/work/SourceCode/petIGA/igakit/igakit/__init__.py)
```
It seems that the fortran library can not linked to python package correctly. My enivornment is Ubuntu22.04 and python3.8. Thanks so much.

**Comment by dalcinl** [comment]
> It seems that the fortran library can not linked to python package correctly.

Without further information, it's very hard to guess what's going on.
Can you paste the output of `pip install -vvv  /home/Users/work/SourceCode/petIGA/igakit`? 
Or any build output that gives me a clue why the Fortran library fails to build?

**Comment by Yihao-Shi** [comment]
It is my output of `pip install -vvv  /home/Users/work/SourceCode/petIGA/igakit`
```
    Skipping link: none of the wheel's tags (pp310-pypy310_pp73-macosx_14_0_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/6e/62/989c4988bde1a8e08117fccc3bab73d2886421fb98cde597168714f3c54e/numpy-2.1.2-pp310-pypy310_pp73-macosx_14_0_x86_64.whl (from https://pypi.org/simple/numpy/) (requires-python:>=3.10)
    Skipping link: none of the wheel's tags (pp310-pypy310_pp73-manylinux2014_x86_64, pp310-pypy310_pp73-manylinux_2_17_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/53/b1/00ef9f30975f1312a53257f68e57b4513d14d537e03d507e2773a684b1e8/numpy-2.1.2-pp310-pypy310_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from https://pypi.org/simple/numpy/) (requires-python:>=3.10)
    Skipping link: none of the wheel's tags (pp310-pypy310_pp73-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/c0/ec/0c04903b48dfea6be1d7b47ba70f98709fb7198fd970784a1400c391d522/numpy-2.1.2-pp310-pypy310_pp73-win_amd64.whl (from https://pypi.org/simple/numpy/) (requires-python:>=3.10)
    Link requires a different Python (3.8.10 not in: '>=3.10'): https://files.pythonhosted.org/packages/4b/d1/8a730ea07f4a37d94f9172f4ce1d81064b7a64766b460378be278952de75/numpy-2.1.2.tar.gz (from https://pypi.org/simple/numpy/) (requires-python:>=3.10)
    Skipping link: 2.1.2 Requires-Python >=3.10: https://files.pythonhosted.org/packages/4b/d1/8a730ea07f4a37d94f9172f4ce1d81064b7a64766b460378be278952de75/numpy-2.1.2.tar.gz (from https://pypi.org/simple/numpy/) (requires-python:>=3.10)
  Skipping link: not a file: https://pypi.org/simple/numpy/
  Given no hashes to check 170 links for project 'numpy': discarding no candidates
  Collecting numpy
    Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/98/5d/5738903efe0ecb73e51eb44feafba32bdba2081263d40c5043568ff60faf/numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
    Created temporary directory: /tmp/pip-unpack-cx4rjk5w
    Looking up "https://files.pythonhosted.org/packages/98/5d/5738903efe0ecb73e51eb44feafba32bdba2081263d40c5043568ff60faf/numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata" in the cache
    Current age based on date: 25158568
    Ignoring unknown cache-control directive: immutable
    Freshness lifetime from max-age: 365000000
    The response is "fresh", returning cached response
    365000000 > 25158568
    Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
  1 location(s) to search for versions of meson:
  * https://pypi.org/simple/meson/
  Fetching project page and analyzing links: https://pypi.org/simple/meson/
  Getting page https://pypi.org/simple/meson/
  Found index url https://pypi.org/simple/
  Looking up "https://pypi.org/simple/meson/" in the cache
  Request header has "max_age" as 0, cache bypassed
  https://pypi.org:443 "GET /simple/meson/ HTTP/1.1" 304 0
  Fetched page https://pypi.org/simple/meson/ as application/vnd.pypi.simple.v1+json
    Found link https://files.pythonhosted.org/packages/a3/04/4bbc35ab9a6f7b8578291916f82ed9421a40da7b6024cd0624624051f4f0/meson-0.29.0.dev1-py3-none-any.whl (from https://pypi.org/simple/meson/), version: 0.29.0.dev1
    Found link https://files.pythonhosted.org/packages/da/95/5ca182db9085b93d9270ad872d1a8a58db184610fb58cef659a5b7a05e4b/patchelf-0.13.0.0.tar.gz (from https://pypi.org/simple/patchelf/), version: 0.13.0.0
    Skipping link: none of the wheel's tags (py2-none-manylinux2014_aarch64, py2-none-manylinux_2_17_aarch64, py2-none-musllinux_1_1_aarch64, py3-none-manylinux2014_aarch64, py3-none-manylinux_2_17_aarch64, py3-none-musllinux_1_1_aarch64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/ca/6f/7f4a84cd283bdf5c3ff78f677bb1eb40cc0103c2d3bea4baf58125ea859f/patchelf-0.13.1.0-py2.py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.musllinux_1_1_aarch64.whl (from https://pypi.org/simple/patchelf/)
 
    Skipping link: none of the wheel's tags (py2-none-musllinux_1_1_i686, py3-none-musllinux_1_1_i686) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/ad/5d/6e97c8a25167d4867694c7fb0b9bdbc9b096d6479c8e56c5bd41b49613f6/ninja-1.11.1.1-py2.py3-none-musllinux_1_1_i686.whl (from https://pypi.org/simple/ninja/)
    Skipping link: none of the wheel's tags (py2-none-musllinux_1_1_ppc64le, py3-none-musllinux_1_1_ppc64le) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/43/78/34af88d753389a9412438d16142c77e587e0d69152faf0bbf99701063dd8/ninja-1.11.1.1-py2.py3-none-musllinux_1_1_ppc64le.whl (from https://pypi.org/simple/ninja/)
    Skipping link: none of the wheel's tags (py2-none-musllinux_1_1_s390x, py3-none-musllinux_1_1_s390x) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/3b/74/de0633f8bced3b188942fca64a950e8f2206c60c10c97af465b356ae9b25/ninja-1.11.1.1-py2.py3-none-musllinux_1_1_s390x.whl (from https://pypi.org/simple/ninja/)
    Skipping link: none of the wheel's tags (py2-none-musllinux_1_1_x86_64, py3-none-musllinux_1_1_x86_64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/9a/f3/3e4a56ff77739d1582749b93497bdebf11e003fbc7a66363ef6c772ebd0a/ninja-1.11.1.1-py2.py3-none-musllinux_1_1_x86_64.whl (from https://pypi.org/simple/ninja/)
    Skipping link: none of the wheel's tags (py2-none-win32, py3-none-win32) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/c5/ee/53df34fcc9c0b1db62b2f2e2c848e28d9354e1c7f0dce029ee50b16ca157/ninja-1.11.1.1-py2.py3-none-win32.whl (from https://pypi.org/simple/ninja/)
    Skipping link: none of the wheel's tags (py2-none-win_amd64, py3-none-win_amd64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/b6/2f/a3bc50fa63fc4fe9348e15b53dc8c87febfd4e0c660fcf250c4b19a3aa3b/ninja-1.11.1.1-py2.py3-none-win_amd64.whl (from https://pypi.org/simple/ninja/)
    Skipping link: none of the wheel's tags (py2-none-win_arm64, py3-none-win_arm64) are compatible (run pip debug --verbose to show compatible tags): https://files.pythonhosted.org/packages/73/2a/f5b7b3b7ecd5cf4e31375580bf5c6a01a328ed1ebdfff90fab463e3f4bc7/ninja-1.11.1.1-py2.py3-none-win_arm64.whl (from https://pypi.org/simple/ninja/)
    Found link https://files.pythonhosted.org/packages/37/2c/d717d13a413d6f7579cdaa1e28e6e2c98de95461549b08d311c8a5bf4c51/ninja-1.11.1.1.tar.gz (from https://pypi.org/simple/ninja/), version: 1.11.1.1
  Skipping link: not a file: https://pypi.org/simple/ninja/
  Given no hashes to check 29 links for project 'ninja': discarding no candidates
  Collecting ninja>=1.8.2
    Obtaining dependency information for ninja>=1.8.2 from https://files.pythonhosted.org/packages/6d/92/8d7aebd4430ab5ff65df2bfee6d5745f95c004284db2d8ca76dcbfd9de47/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata
    Created temporary directory: /tmp/pip-unpack-umw7ie4t
    Looking up "https://files.pythonhosted.org/packages/6d/92/8d7aebd4430ab5ff65df2bfee6d5745f95c004284db2d8ca76dcbfd9de47/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata" in the cache
    Current age based on date: 85171
    Ignoring unknown cache-control directive: immutable
    Freshness lifetime from max-age: 365000000
    The response is "fresh", returning cached response
    365000000 > 85171
    Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl.metadata (5.3 kB)
  Created temporary directory: /tmp/pip-unpack-849_dlis
  Looking up "https://files.pythonhosted.org/packages/c6/73/c3105c973dd2afcdc5d946ee211d5c4ecdf9d27bb54ae835b144e706e86d/patchelf-0.17.2.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.musllinux_1_1_x86_64.whl" in the cache
  Current age based on date: 85171
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 85171
  Using cached patchelf-0.17.2.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.musllinux_1_1_x86_64.whl (425 kB)
  Downloading link https://files.pythonhosted.org/packages/c6/73/c3105c973dd2afcdc5d946ee211d5c4ecdf9d27bb54ae835b144e706e86d/patchelf-0.17.2.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.musllinux_1_1_x86_64.whl (from https://pypi.org/simple/patchelf/) to /tmp/pip-unpack-849_dlis/patchelf-0.17.2.1-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.musllinux_1_1_x86_64.whl
  Looking up "https://files.pythonhosted.org/packages/6d/92/8d7aebd4430ab5ff65df2bfee6d5745f95c004284db2d8ca76dcbfd9de47/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl" in the cache
  Current age based on date: 85171
  Ignoring unknown cache-control directive: immutable
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 85171
  Using cached ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (307 kB)
  Downloading link https://files.pythonhosted.org/packages/6d/92/8d7aebd4430ab5ff65df2bfee6d5745f95c004284db2d8ca76dcbfd9de47/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl (from https://pypi.org/simple/ninja/) to /tmp/pip-unpack-849_dlis/ninja-1.11.1.1-py2.py3-none-manylinux1_x86_64.manylinux_2_5_x86_64.whl
  WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.43ubuntu1'
  Installing collected packages: patchelf, ninja


    changing mode of /tmp/pip-build-env-28o9o7us/normal/bin/ninja to 775
  Successfully installed ninja-1.11.1.1 patchelf-0.17.2.1
  Removed build tracker: '/tmp/pip-build-tracker-cmxyucf2'
  Installing backend dependencies ... done
  Created temporary directory: /tmp/pip-modern-metadata-hk5zki3g
  Running command Preparing metadata (pyproject.toml)
  + meson setup /home/Users/work/SourceCode/petIGA/igakit /home/Users/work/SourceCode/petIGA/igakit/.mesonpy-kx1c92rk -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/home/Users/work/SourceCode/petIGA/igakit/.mesonpy-kx1c92rk/meson-python-native-file.ini
  The Meson build system
  Version: 1.6.0
  Source dir: /home/Users/work/SourceCode/petIGA/igakit
  Build dir: /home/Users/work/SourceCode/petIGA/igakit/.mesonpy-kx1c92rk
  Build type: native build
  Project name: igakit
  Project version: 0.1.0
  Fortran compiler for the host machine: gfortran (gcc 11.2.0 "GNU Fortran (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
  Fortran linker for the host machine: gfortran ld.bfd 2.38
  C compiler for the host machine: cc (gcc 11.2.0 "cc (Ubuntu 11.2.0-19ubuntu1) 11.2.0")
  C linker for the host machine: cc ld.bfd 2.38
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Program python found: YES (/usr/bin/python)
  Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
  Run-time dependency python found: YES 3.8
  Compiler for C supports arguments -Wno-misleading-indentation: YES
  Build targets in project: 2

  igakit 0.1.0

    User defined options
      Native files: /home/Users/work/SourceCode/petIGA/igakit/.mesonpy-kx1c92rk/meson-python-native-file.ini
      b_ndebug    : if-release
      b_vscrt     : md
      buildtype   : release

  Found ninja-1.11.1.git.kitware.jobserver-1 at /tmp/pip-build-env-28o9o7us/normal/bin/ninja
  + /tmp/pip-build-env-28o9o7us/normal/bin/ninja
  [1/7] Compiling C object igalib.cpython-38-x86_64-linux-gnu.so.p/b5f1294687c5e378df1d75fc40c46076b4589b77_site-packages_numpy_f2py_src_fortranobject.c.o
  [2/7] Generating igalibmodule.c with a custom command
  Reading fortran codes...
        Reading file '../igakit/igalib.pyf' (format:free)
  Post-processing...
        Block: igalib
                        Block: bsp
                                Block: FindSpan
                                Block: FindMult
                                Block: FindSpanMult
                                Block: EvalBasisFuns
                                Block: EvalBasisFunsDers
                                Block: SpanIndex
                                Block: Greville
                                Block: InsertKnot
                                Block: RemoveKnot
                                Block: Clamp
                                Block: Unclamp
                                Block: RefineKnotVector
                                Block: DegreeElevate
                                Block: Extract
                                Block: Evaluate0
                                Block: Evaluate1
                                Block: Evaluate2
                                Block: Evaluate3
                                Block: Gradient1
                                Block: Gradient2
                                Block: Gradient3
                                Block: Hessian1
                                Block: Hessian2
                                Block: Hessian3
                                Block: ThirdDer1
                                Block: ThirdDer2
                                Block: ThirdDer3
                                Block: FourthDer1
                                Block: FourthDer2
                                Block: FourthDer3
                        Block: iga
                                Block: KnotVector
                                Block: GaussLegendreRule
                                Block: GaussLobattoRule
                                Block: BasisData
                                Block: Greville
                                Block: BasisDataCol
  Applying post-processing hooks...
    character_backward_compatibility_hook
  Post-processing (stage 2)...
        Block: igalib
                Block: unknown_interface
                        Block: bsp
                                Block: FindSpan
                                Block: FindMult
                                Block: FindSpanMult
                                Block: EvalBasisFuns
                                Block: EvalBasisFunsDers
                                Block: SpanIndex
                                Block: Greville
                                Block: InsertKnot
                                Block: RemoveKnot
                                Block: Clamp
                                Block: Unclamp
                                Block: RefineKnotVector
                                Block: DegreeElevate
                                Block: Extract
                                Block: Evaluate0
                                Block: Evaluate1
                                Block: Evaluate2
                                Block: Evaluate3
                                Block: Gradient1
                                Block: Gradient2
                                Block: Gradient3
                                Block: Hessian1
                                Block: Hessian2
                                Block: Hessian3
                                Block: ThirdDer1
                                Block: ThirdDer2
                                Block: ThirdDer3
                                Block: FourthDer1
                                Block: FourthDer2
                                Block: FourthDer3
                        Block: iga
                                Block: KnotVector
                                Block: GaussLegendreRule
                                Block: GaussLobattoRule
                                Block: BasisData
                                Block: Greville
                                Block: BasisDataCol
  Building modules...
      Building module "igalib"...
                Constructing F90 module support for "bsp"...
              Constructing wrapper function "bsp.FindSpan"...
                span = FindSpan(p,U,u)
              Constructing wrapper function "bsp.FindMult"...
                mult = FindMult(p,U,u,[span])
              Constructing wrapper function "bsp.FindSpanMult"...
                span,mult = FindSpanMult(p,U,u)
              Constructing wrapper function "bsp.EvalBasisFuns"...
                N = EvalBasisFuns(p,U,u,[span])
              Constructing wrapper function "bsp.EvalBasisFunsDers"...
                dN = EvalBasisFunsDers(p,U,u,[d,span])
              Constructing wrapper function "bsp.SpanIndex"...
                ID = SpanIndex(p,U)
              Constructing wrapper function "bsp.Greville"...
                X = Greville(p,U)
              Constructing wrapper function "bsp.InsertKnot"...
                V,Qw = InsertKnot(p,U,Pw,u,[r])
              Constructing wrapper function "bsp.RemoveKnot"...
                t,V,Qw = RemoveKnot(p,U,Pw,u,TOL,[r])
              Constructing wrapper function "bsp.Clamp"...
                V,Qw = Clamp(p,U,Pw,[l,r])
              Constructing wrapper function "bsp.Unclamp"...
                V,Qw = Unclamp(p,U,Pw,[C,l,r])
              Constructing wrapper function "bsp.RefineKnotVector"...
                V,Qw = RefineKnotVector(p,U,Pw,X)
              Constructing wrapper function "bsp.DegreeElevate"...
                V,Qw = DegreeElevate(p,U,Pw,t)
              Constructing wrapper function "bsp.Extract"...
                Cw = Extract(p,U,Pw,uu)
              Constructing wrapper function "bsp.Evaluate0"...
                Cw = Evaluate0(Pw)
              Constructing wrapper function "bsp.Evaluate1"...
                Cw = Evaluate1(p,U,Pw,X)
              Constructing wrapper function "bsp.Evaluate2"...
                Cw = Evaluate2(px,Ux,py,Uy,Pw,X,Y)
              Constructing wrapper function "bsp.Evaluate3"...
                Cw = Evaluate3(px,Ux,py,Uy,pz,Uz,Pw,X,Y,Z)
              Constructing wrapper function "bsp.Gradient1"...
                G = Gradient1(map,px,Ux,Pw,F,X)
              Constructing wrapper function "bsp.Gradient2"...
                G = Gradient2(map,px,Ux,py,Uy,Pw,F,X,Y)
              Constructing wrapper function "bsp.Gradient3"...
                G = Gradient3(map,px,Ux,py,Uy,pz,Uz,Pw,F,X,Y,Z)
              Constructing wrapper function "bsp.Hessian1"...
                H = Hessian1(map,px,Ux,Pw,F,X)
              Constructing wrapper function "bsp.Hessian2"...
                H = Hessian2(map,px,Ux,py,Uy,Pw,F,X,Y)
              Constructing wrapper function "bsp.Hessian3"...
                H = Hessian3(map,px,Ux,py,Uy,pz,Uz,Pw,F,X,Y,Z)
              Constructing wrapper function "bsp.ThirdDer1"...
                D3 = ThirdDer1(map,px,Ux,Pw,F,X)
              Constructing wrapper function "bsp.ThirdDer2"...
                D3 = ThirdDer2(map,px,Ux,py,Uy,Pw,F,X,Y)
              Constructing wrapper function "bsp.ThirdDer3"...
                D3 = ThirdDer3(map,px,Ux,py,Uy,pz,Uz,Pw,F,X,Y,Z)
              Constructing wrapper function "bsp.FourthDer1"...
                D4 = FourthDer1(map,px,Ux,Pw,F,X)
              Constructing wrapper function "bsp.FourthDer2"...
                D4 = FourthDer2(map,px,Ux,py,Uy,Pw,F,X,Y)
              Constructing wrapper function "bsp.FourthDer3"...
                D4 = FourthDer3(map,px,Ux,py,Uy,pz,Uz,Pw,F,X,Y,Z)
                Constructing F90 module support for "iga"...
              Constructing wrapper function "iga.KnotVector"...
                U = KnotVector(E,p,[C,Ui,Uf,wrap])
              Constructing wrapper function "iga.GaussLegendreRule"...
                X,W = GaussLegendreRule(q)
              Constructing wrapper function "iga.GaussLobattoRule"...
                X,W = GaussLobattoRule(q)
              Constructing wrapper function "iga.BasisData"...
                O,J,W,X,N = BasisData(p,U,[d,q])
              Constructing wrapper function "iga.Greville"...
                X = Greville(p,U)
              Constructing wrapper function "iga.BasisDataCol"...
                O,N = BasisDataCol(p,U,X,[d])
      Wrote C/API module "igalib" to file "./igalibmodule.c"
      Fortran 90 wrappers are saved to "./igalib-f2pywrappers2.f90"
  [3/7] Module scanner.
  [4/7] Compiling C object igalib.cpython-38-x86_64-linux-gnu.so.p/meson-generated_.._igalibmodule.c.o
  igalibmodule.c: In function ‘int_from_pyobj’:
  igalibmodule.c:123:14: warning: implicit declaration of function ‘Npy__PyLong_AsInt’ [-Wimplicit-function-declaration]
    123 |         *v = Npy__PyLong_AsInt(obj);
        |              ^~~~~~~~~~~~~~~~~
  igalibmodule.c: In function ‘PyInit_igalib’:
  igalibmodule.c:8154:5: warning: implicit declaration of function ‘Py_SET_TYPE’; did you mean ‘Py_TYPE’? [-Wimplicit-function-declaration]
   8154 |     Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
        |     ^~~~~~~~~~~
        |     Py_TYPE
  [5/7] Compiling Fortran object igalib.cpython-38-x86_64-linux-gnu.so.p/igakit_igalib.f90.o
  [6/7] Compiling Fortran object igalib.cpython-38-x86_64-linux-gnu.so.p/meson-generated_.._igalib-f2pywrappers2.f90.o
  [7/7] Linking target igalib.cpython-38-x86_64-linux-gnu.so
  [1/10] /home/Users/work/SourceCode/petIGA/igakit/.mesonpy-kx1c92rk/igalib.cpython-38-x86_64-linux-gnu.so
  [2/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/__init__.py
  [3/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/cad.py
  [4/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/io.py
  [5/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/nurbs.py
  [6/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/plot_mpl.py
  [7/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/plot_myv.py
  [8/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/plot_nul.py
  [9/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/plot.py
  [10/10] /home/Users/work/SourceCode/petIGA/igakit/igakit/transform.py
  Preparing metadata (pyproject.toml) ... done
  Source in ./work/SourceCode/petIGA/igakit has version 0.1.0, which satisfies requirement igakit==0.1.0 from file:///home/Users/work/SourceCode/petIGA/igakit
  Removed igakit==0.1.0 from file:///home/Users/work/SourceCode/petIGA/igakit from build tracker '/tmp/pip-build-tracker-cmxyucf2'
Requirement already satisfied: numpy in ./.local/lib/python3.8/site-packages (from igakit==0.1.0) (1.23.5)
Created temporary directory: /tmp/pip-unpack-mlnsgdk9
Building wheels for collected packages: igakit
  Created temporary directory: /tmp/pip-wheel-99ab2ay8
  Destination directory: /tmp/pip-wheel-99ab2ay8
  Running command Building wheel for igakit (pyproject.toml)
  Building wheel for igakit (pyproject.toml) ... done
  Created wheel for igakit: filename=igakit-0.1.0-cp38-cp38-linux_x86_64.whl size=129858 sha256=52f3ba9cf9cb99ab0bbaafd5a359afaac222c1769d61a78af04cc43ecb3e09b2
  Stored in directory: /tmp/pip-ephem-wheel-cache-9qqovhzq/wheels/76/09/85/320e8565f39e66c4baa1ab8d6a4bd9b7c8ba2a13431d141a3d
Successfully built igakit
WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.43ubuntu1'
Installing collected packages: igakit
  Attempting uninstall: igakit
    Found existing installation: igakit 0.1.0
    Uninstalling igakit-0.1.0:
      Created temporary directory: /home/Users/.local/lib/python3.8/site-packages/~gakit-0.1.0.dist-info
      Removing file or directory /home/Users/.local/lib/python3.8/site-packages/igakit-0.1.0.dist-info/
      Created temporary directory: /home/Users/.local/lib/python3.8/site-packages/~gakit
      Removing file or directory /home/Users/.local/lib/python3.8/site-packages/igakit/
      Successfully uninstalled igakit-0.1.0

Successfully installed igakit-0.1.0
Disabling truststore because Python version isn't 3.10+
Remote version of pip: 24.3.1
Local version of pip:  24.3.1
Was pip installed by pip? True
Removed build tracker: '/tmp/pip-build-tracker-cmxyucf2'
```
Is that means python >= 3.10 is needed?

**Comment by Yihao-Shi** [comment]
The output of `python -m pip install .` is also given:
```
Defaulting to user installation because normal site-packages is not writeable
Processing /home/Users/work/SourceCode/petIGA/igakit
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/Users/.local/lib/python3.8/site-packages (from igakit==0.1.0) (1.23.5)
Building wheels for collected packages: igakit
  Building wheel for igakit (pyproject.toml) ... done
  Created wheel for igakit: filename=igakit-0.1.0-cp38-cp38-linux_x86_64.whl size=129858 sha256=22e82447d80fb32cde5e4fa3f1eaeaa627da2c7e9480440328218373403b8ccc
  Stored in directory: /tmp/pip-ephem-wheel-cache-xdvw5ljt/wheels/76/09/85/320e8565f39e66c4baa1ab8d6a4bd9b7c8ba2a13431d141a3d
Successfully built igakit
WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.43ubuntu1'
Installing collected packages: igakit
  Attempting uninstall: igakit
    Found existing installation: igakit 0.1.0
    Uninstalling igakit-0.1.0:
      Successfully uninstalled igakit-0.1.0
Successfully installed igakit-0.1.0
```

**Comment by dalcinl** [comment]
Python 3.8 is quite old by now, it is even EOL. This is for sure some incompatibility between the old Python and NumPy versions and the new meson-python build backend igakit is using (because of newer Python's and NumPy's).

You may be able to install igakit if you try a previous commit, let say
```console
cd igakit
git checkout 2233af7d55727c88f6f9428415c2fdc5b6c5fbfc
python -m pip cache remove igakit
python -m pip install .
```

**Comment by Yihao-Shi** [comment]
thank you
